spring:
  application:
    name: bc-spring-app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mustafa

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      boot:allow_jdbc_metadata_access: false

